### PR TITLE
Update docker build

### PR DESCRIPTION
**Pull request by macyabbey**
- Adds muti-platform support to go commands
- Changed to three stage build so ui and go build are mostly parallel and final stage does not have any of the files used for building.
- Tweaked pubish github workflow to minimally publish containers for two platforms, `linux/amd64` and `linux/arm64`

### CODE REVIEW

**Comment by macyabbey** [comment]
@daveshanley for your consideration

**Comment by daveshanley** [comment]
Would you be able to fix the conflict?

**Comment by macyabbey** [comment]
> Would you be able to fix the conflict?

@daveshanley Sure thing - fixed conflict. 

Also noticed the runner still had ~300 MB from go that wasn't needed. Down to about ~36 MB on the runner.

**Comment by daveshanley** [comment]
I just tried this, 38mb on my machine! woo, nice job, thank you for this Docker kung-fu.

**Pull request merged**
