### PR TITLE
Use all property examples in generated mock responses

### PR DESCRIPTION
**Pull request by martinsirbe**
Currently when the response mock engine generates a response using the `MockGenerator`, the generated responses contain only examples for individual properties that are marked as required, see tests for more details.

The reason why generated responses contain only examples for required properties is a side-effect of using mock generator for validation. While it makes sense for validating required fields for requests, it shouldn't affect the response generation.

Changes:
* By default, disables the required check on the response mock engine to ensure that all examples for individual properties are used in generated mock responses.
* Introduces a new configuration option, `enable-all-mock-response-fields`, to allow only the use of required field examples in the generated mock responses when set to `false`.

This fix uses https://github.com/pb33f/libopenapi/pull/295

### CODE REVIEW

**Review by daveshanley — CHANGES_REQUESTED** [review]
I think this needs to be a configurable switch, I am OK with the default being set to off, but there needs to be a way to turn it on via the configuration.

**Comment by martinsirbe** [comment]
> I think this needs to be a configurable switch, I am OK with the default being set to off, but there needs to be a way to turn it on via the configuration.

I agree that this makes sense. I suggest using the Go variadic Option pattern for configuring the mock engine on initialisation. This allows us to add optional configuration without breaking the `NewMockEngine` initialisation function signature. Another approach could be to add a new function on `MockEngine` to enable the required check, but I prefer the first option for its flexibility and non-breaking nature.

Thank you for your input and guidance! If you have other ideas or suggestions, I'd love to hear them too.

**Comment by daveshanley** [comment]
As long as the ability to 'enable all mock fields' when in mock mode exists as part of the wiretap config (https://pb33f.io/wiretap/configuring/) then the first option sounds OK to me.

**Review by daveshanley — APPROVED** [review]
LGTM! Thank you for your contribution!

**Pull request merged**
