### PR TITLE
OPENAPI: the rewrite header key formatting is wrong in code

### PR DESCRIPTION
**Pull request by jacobm-splunk**
There are multiple possible formatting possibilities for header values.

This MR ensures that a variety of header formatting methods are supported for the RewriteId feature.

### CODE REVIEW

**Comment by daveshanley** [comment]
Can you help me understand why we need variations? It's a custom header?

**Comment by jacobm-splunk** [comment]
> Can you help me understand why we need variations? It's a custom header?

I want it to be as user-friendly as possible. 

The header needs to be set by a user, and it's not super clear when the header is incorrect. I want to make wiretap give a user the best possible opportunity to set the correct rewrite id header.

I can remove that if we don't want it.

**Comment by daveshanley** [comment]
Got it. 

Thanks.

**Review by daveshanley — APPROVED** [review]
LGTM

**Pull request merged**
